# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_full_name_cyrillic', models.CharField(default='Гарри Поттер Эванс Верес', max_length=300, verbose_name='Full name (Cyrillic transcription)/ФИО (Кириллическая транскрипция)')),
                ('visa_full_name_latin', models.CharField(default='Albus Persival Wulfric Brayan Damboldor', max_length=300, verbose_name='Full name(Latin transcription)/ФИО (Латинская транскрипция)')),
                ('visa_sex', models.CharField(choices=[('Мужской/Male', 'Мужской/Male'), ('Женский/Female', 'Женский/Female')], default='Мужской/Male', max_length=50, verbose_name='Пол')),
                ('visa_date_birthday', models.DateField(verbose_name='Date of birth/Дата рождения')),
                ('visa_data_city', models.CharField(max_length=150, verbose_name='Place of birth/Место рождения')),
                ('visa_citizenship', models.CharField(max_length=150, verbose_name='Nationality/Гражданство')),
                ('visa_father_name', models.CharField(max_length=200, verbose_name="Father's name/Имя отца")),
                ('visa_mother_name', models.CharField(max_length=200, verbose_name="Mother's name/Имя матери")),
                ('visa_occupation', models.CharField(max_length=400, verbose_name='Occupation/Место работы и должность')),
                ('visa_passport_number', models.IntegerField(verbose_name='Passport number/Номер загран-паспорта')),
                ('visa_passport_end', models.DateField(verbose_name='Date of expiry/Дата окончания')),
                ('visa_passport_city', models.CharField(max_length=100, verbose_name='Country of issue/Страна выдачи')),
                ('visa_hotel_address', models.CharField(max_length=150, verbose_name='Address of hotel lodging in Cyprus/Адрес гостиницы размещения на кипре')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
            },
        ),
    ]
