//- order
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SELECT_ENTITY = 'SELECT_ENTITY'; 
export const SELECT_ENTITIES = 'SELECT_ENTITIES';
export const REQUEST_ENTITIES = 'REQUEST_ENTITIES';
export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';
export const INVALIDATE_ENTITIES = 'INVALIDATE_ENTITIES';
export const VisibilityFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_COMPLETED: 'SHOW_COMPLETED',
	SHOW_ACTIVE: 'SHOW_ACTIVE'
};
