# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barter_number', models.CharField(max_length=300, verbose_name='Порядковый номер')),
                ('barter_date_start', models.DateField(verbose_name='Дата начала бартера')),
                ('barter_date_expiration', models.DateField(verbose_name='Дата окончания бартера')),
                ('barter_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Artists', verbose_name='Артист')),
                ('barter_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Contractors', verbose_name='Подрядчик')),
                ('barter_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Employers', verbose_name='Мэнеджер')),
                ('barter_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Partners', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Бартер',
                'verbose_name_plural': 'Бартер',
            },
        ),
    ]
