# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barters',
            options={'verbose_name': 'Бартер', 'verbose_name_plural': 'Бартеры'},
        ),
    ]
