//- order
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SELECT_ORDERS = 'SELECT_ORDERS';
export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const VisibilityFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_COMPLETED: 'SHOW_COMPLETED',
	SHOW_ACTIVE: 'SHOW_ACTIVE'
};
