# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='saturday',
            field=models.CharField(max_length=100, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='places',
            name='sunday',
            field=models.CharField(max_length=100, verbose_name='Воскресенье'),
        ),
    ]
