# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('places', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порядковы номер')),
                ('adventure_transfer_there_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Трансфер туда - Время отбытия')),
                ('adventure_transfer_there_departure', models.DateTimeField(blank=True, null=True, verbose_name='Трансфер туда - Время прибытия')),
                ('adventure_transfer_back_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Трасфер обратно - Время отбытия')),
                ('adventure_transfer_back_departure', models.DateTimeField(blank=True, null=True, verbose_name='Трасфер обратно - Время прибытия')),
                ('adventure_by_yourself_there_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Самостоятельно туда - Время отбытия')),
                ('adventure_by_yourself_there_departure', models.DateTimeField(blank=True, null=True, verbose_name='Самостоятельно туда - Время прибытия')),
                ('adventure_by_yourself_back_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Самостоятельно обратно - Время отбытия')),
                ('adventure_by_yourself_back_departure', models.DateTimeField(blank=True, null=True, verbose_name='Самостоятельно обратно - Время прибытия')),
                ('adventure_accommodation_settlement', models.DateTimeField(blank=True, null=True, verbose_name='Заселение')),
                ('adventure_accommodation_eviction', models.DateTimeField(blank=True, null=True, verbose_name='Выселение')),
                ('adventure_room_type', models.CharField(choices=[('SNGL', 'SNGL'), ('DBL', 'DBL'), ('TWN TRPL', 'TWN TRPL'), ('DE LUXE', 'DE LUXE'), ('Business', 'Business'), ('Apartment', 'Apartment'), ('President', 'President')], max_length=50, verbose_name='Тип номера')),
                ('adventure_room_number', models.IntegerField(verbose_name='Номер комнаты')),
                ('adventure_room_night_quantity', models.IntegerField(verbose_name='Колличество ночей')),
                ('adventure_room_additional_night_quantity', models.IntegerField(verbose_name='Колличество ночей')),
                ('adventure_room_additional_supplement', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма доплаты')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('adventure_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Customers', verbose_name='Клиент')),
                ('adventure_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150, verbose_name='Название')),
                ('event_date', models.DateField(verbose_name='Дата')),
                ('event_people_quantity', models.IntegerField(verbose_name='Колличество человек')),
                ('event_wish', models.TextField(max_length=300, verbose_name='Пожелание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('event_artists', models.ManyToManyField(to='people.Artists', verbose_name='Артисты')),
                ('event_customers', models.ManyToManyField(to='people.Customers', verbose_name='Менеджеры')),
                ('event_places', models.ManyToManyField(to='places.Places', verbose_name='Место проведения')),
                ('event_type', models.ManyToManyField(to='app.EventTypes', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
